### PR TITLE
active pages are highlighted

### PR DESCRIPTION
**Pull request by jvberdec**
It isn't the prettiest, but had issues implementing this with css conflicting with bootstrap. I just blocked out part of the index and added the blocked bits to their respective files.

### CODE REVIEW

**Comment by Quetourah** [comment]
> It isn't the prettiest, but had issues implementing this with css conflicting with bootstrap. I just blocked out part of the index and added the blocked bits to their respective files.

Hey, @jvberdec. It looks great! However, since you said it was hard to do with CSS, I think making the changes in `views.py` could help. I think this approach from this article (https://medium.com/@dustindavignon/django-2-0-make-clicked-tab-active-with-bootstrap-de27a74f6b76) is straight forward and helps us keep all the navbar info in one file.

We can update the function adding the context like this:
```
def index(request):
      context = {"home_page": "active"} # new info here
return render(request, 'pages/index.html', context)
```
and the class in `index.html` like this:

```
class="nav-item {{ home_page }}
```

**Comment by jvberdec** [comment]
> > It isn't the prettiest, but had issues implementing this with css conflicting with bootstrap. I just blocked out part of the index and added the blocked bits to their respective files.
> 
> Hey, @jvberdec. It looks great! However, since you said it was hard to do with CSS, I think making the changes in `views.py` could help. I think this approach from this article (https://medium.com/@dustindavignon/django-2-0-make-clicked-tab-active-with-bootstrap-de27a74f6b76) is straight forward and helps us keep all the navbar info in one file.
> 
> We can update the function adding the context like this:
> 
> ```
> def index(request):
>       context = {"home_page": "active"} # new info here
> return render(request, 'pages/index.html', context)
> ```
> 
> and the class in `index.html` like this:
> 
> ```
> class="nav-item {{ home_page }}
> ```

Okay, will do thank you!

**Comment by Quetourah** [comment]
> > > It isn't the prettiest, but had issues implementing this with css conflicting with bootstrap. I just blocked out part of the index and added the blocked bits to their respective files.
> > 
> > 
> > Hey, @jvberdec. It looks great! However, since you said it was hard to do with CSS, I think making the changes in `views.py` could help. I think this approach from this article (https://medium.com/@dustindavignon/django-2-0-make-clicked-tab-active-with-bootstrap-de27a74f6b76) is straight forward and helps us keep all the navbar info in one file.
> > We can update the function adding the context like this:
> > ```
> > def index(request):
> >       context = {"home_page": "active"} # new info here
> > return render(request, 'pages/index.html', context)
> > ```
> > 
> > 
> > and the class in `index.html` like this:
> > ```
> > class="nav-item {{ home_page }}
> > ```
> 
> Okay, will do thank you!

np! 😃

**Comment by jvberdec** [comment]
> > > > It isn't the prettiest, but had issues implementing this with css conflicting with bootstrap. I just blocked out part of the index and added the blocked bits to their respective files.
> > > 
> > > 
> > > Hey, @jvberdec. It looks great! However, since you said it was hard to do with CSS, I think making the changes in `views.py` could help. I think this approach from this article (https://medium.com/@dustindavignon/django-2-0-make-clicked-tab-active-with-bootstrap-de27a74f6b76) is straight forward and helps us keep all the navbar info in one file.
> > > We can update the function adding the context like this:
> > > ```
> > > def index(request):
> > >       context = {"home_page": "active"} # new info here
> > > return render(request, 'pages/index.html', context)
> > > ```
> > > 
> > > 
> > > and the class in `index.html` like this:
> > > ```
> > > class="nav-item {{ home_page }}
> > > ```
> > 
> > 
> > Okay, will do thank you!
> 
> np! 😃

@Quetourah I implemented this method.. I wish I came across it a lot sooner.

**Comment by Quetourah** [comment]
> > > > > It isn't the prettiest, but had issues implementing this with css conflicting with bootstrap. I just blocked out part of the index and added the blocked bits to their respective files.
> > > > 
> > > > 
> > > > Hey, @jvberdec. It looks great! However, since you said it was hard to do with CSS, I think making the changes in `views.py` could help. I think this approach from this article (https://medium.com/@dustindavignon/django-2-0-make-clicked-tab-active-with-bootstrap-de27a74f6b76) is straight forward and helps us keep all the navbar info in one file.
> > > > We can update the function adding the context like this:
> > > > ```
> > > > def index(request):
> > > >       context = {"home_page": "active"} # new info here
> > > > return render(request, 'pages/index.html', context)
> > > > ```
> > > > 
> > > > 
> > > > and the class in `index.html` like this:
> > > > ```
> > > > class="nav-item {{ home_page }}
> > > > ```
> > > 
> > > 
> > > Okay, will do thank you!
> > 
> > 
> > np! 😃
> 
> @Quetourah I implemented this method.. I wish I came across it a lot sooner.

it looks great! just need to fix the tests now

**Comment by jvberdec** [comment]
The credit cards are displayed on a new page, along with a new caption. Button has been added to redirect back to the form. 

Note: The user returns to an empty form for right now. If we want to change it so that the user can see previously entered values, that can be done tomorrow.

**Pull request merged**
